workflows:
  ios-no-firebase:
    name: iOS Build Without Firebase
    max_build_duration: 45
    environment:
      flutter: "3.6.0"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter precache
        script: |
          flutter precache --ios
      - name: Install CocoaPods (No Firebase)
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/Release-iphoneos/Runner.app
