workflows:

  flutter-ios-simulator:

    name: Flutter iOS Simulator

    environment:

      flutter: 3.27.3

      xcode: 16.2

    scripts:

      - flutter build ios --simulator   # --flavor is optional

    artifacts:

      - build/ios/iphonesimulator/Runner.app