workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: "3.6.0"
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: "release"
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Set up signing certificate
        script: |
          app-store-connect fetch-signing-files "com.podemeraldsltd.pelevo" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Clean and prepare build environment
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods/ Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..
      - name: Fix Firebase Headers
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Clean and Reinstall Firebase
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=3.6.0 \
            --build-number=5
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
